CREATE TABLE IF NOT EXISTS `SCHED_SCHOOL_YEAR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `END_DATE` date DEFAULT NULL,
  `NAME` varchar(180) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `SCHOOL_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SCHOOL_ID_KEY` (`SCHOOL_ID`),
  CONSTRAINT `FK_SCHOOLID` FOREIGN KEY (`SCHOOL_ID`) REFERENCES `SCL_SCHOOL` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

