CREATE TABLE IF NOT EXISTS `SCHED_SCHOOL_YEAR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `END_DATE` date DEFAULT NULL,
  `NAME` varchar(180) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `SCHOOL_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SCHOOL_ID_KEY` (`SCHOOL_ID`),
  CONSTRAINT `FK_SCHOOLID` FOREIGN KEY (`SCHOOL_ID`) REFERENCES `SCL_SCHOOL` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SCHED_GRADING_PERIOD` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `END_DATE` date DEFAULT NULL,
  `NAME` varchar(180) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `SCHOOL_YEAR_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SCHOOL_YEAR_ID` (`SCHOOL_YEAR_ID`),
  CONSTRAINT `FK_SCHOOL_YEAR_ID` FOREIGN KEY (`SCHOOL_YEAR_ID`) REFERENCES `SCHED_SCHOOL_YEAR` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SCHED_CLS_TIME_BLOCK` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `END_HOUR` int(11) DEFAULT NULL,
  `END_MINUTES` int(11) DEFAULT NULL,
  `NAME` varchar(180) DEFAULT NULL,
  `START_HOUR` int(11) DEFAULT NULL,
  `START_MINUTES` int(11) DEFAULT NULL,
  `GRADING_PERIOD_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_GRADING_PERIOD_ID` (`GRADING_PERIOD_ID`),
  CONSTRAINT `FK_GRADING_PERIOD_ID` FOREIGN KEY (`GRADING_PERIOD_ID`) REFERENCES `SCHED_GRADING_PERIOD` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SCHED_CLS_TIME_BLOCK_TEMPLATE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `END_HOUR` int(11) DEFAULT NULL,
  `END_MINUTES` int(11) DEFAULT NULL,
  `NAME` varchar(180) DEFAULT NULL,
  `START_HOUR` int(11) DEFAULT NULL,
  `START_MINUTES` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SCHED_SCHOOL_YEAR_TEMPLATE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `END_DATE` date DEFAULT NULL,
  `NAME` varchar(180) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SCHED_GRADING_PERIOD_TEMPLATE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `END_DATE` date DEFAULT NULL,
  `NAME` varchar(180) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;